=== specifiedram98871/Webprojects/5th sem web/lab4/library.dtd
<!ELEMENT library (book+)>
<!ELEMENT book (title, author, publicationYear, ISBN)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (firstName, lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT publicationYear (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ATTLIST book ISBN ID #REQUIRED>
<!ATTLIST publicationYear CDATA #REQUIRED>

=== specifiedram98871/Webprojects/5th sem web/lab4/lab42.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "library.dtd">
<library>
    <book>
        <title>Introduction to XML</title>
        <author>
            <firstName>John</firstName>
            <lastName>Doe</lastName>
        </author>
        <publicationYear>2020</publicationYear>
        <ISBN>ISBN-2020-001</ISBN>
    </book>

    <book>
        <title>Programming in Java</title>
        <author>
            <firstName>Jane</firstName>
            <lastName>Smith</lastName>
        </author>
        <publicationYear>2019</publicationYear>
        <ISBN>ISBN-2019-002</ISBN>
    </book>

    <!-- Add more books as needed -->

</library>
